var words = {
  "title": [
    "Computer-Aided Instruction with Voice Recognition system",
    "Holistic Computerized Faculty Evaluation System",
    "Book Catalog Application using Android",
    "Hotel Reservation Application with Mobile Compatibility in Android",
    "SMS-Based Grade Inquiry System",
    "Mobile Voting System using Android",
    "Grade Viewer Application in Android",
    "SSG Management System with SMS Notification",
    "Payroll System with Biometric and Barcode Technology",
    "School Event Attendance Monitoring System with Biometric and Barcode Technology",
    "Face Recognition System",
    "Android – Controlled Car",
    "Motorcycle Tracking with GPS using Android",
    "Mobile Educational Application for Elementary Student using Android",
    "Class Time Table in Android",
    "Online Grade Inquiry",
    "WEB-BASED TRACKING SYSTEM",
    "Online Grading System",
    "Airline Reservation System",
    "Video Library Management System",
    "Internet Cafe System",
    "Billing System",
    "Electronic Police Clearance System",
    "Salon System",
    "Human Resource Management System",
    "Online billing system",
    "Online membership and billing system",
    "Online class scheduling system",
    "Online POS(Point of Sale)",
    "Online inventory system",
    "Online payroll system",
    "Online ordering system",
    "Online bidding system",
    "Voting system",
    "Online voting system",
    "Online shopping cart",
    "Medical records system",
    "Client server based guidance system",
    "On-line courseware",
    "Payroll system",
    "Hotel reservation system",
    'Hotel management system',
    'Online hotel reservation system',
    'Online public access catalog',
    'Library system',
    'Record management system',
    'Supply inventory system',
    'E-learning system',
    'Hospital system',
    'E-voting system',
    'Online management system',
    'Online Lot Reservation',
    'Online Product Reservation System',
    'Android-Based Class Attendance Monitoring Application using Barcode',
    'Lending Management system',
    'Veterinary Clinic and Pet Shop Management System',
    'Android Joystick Application using Bluetooth',
    'Mobile Point-Of-Sale Application with SMS Notification',
    'Group Messenger Application using Android',
    'Medicine Inventory and Patient Information system',
    'Resort Management System',
    'Mobile Reservation for Banquet Halls',
    'E-Learning System',
    'E-Voting System with SMS technology',
    'On Route Travel Assistant for Public Transport Based on Android Technology',
    'Camera-Based Heart Rate Detector using Android',
    'Mobile Health Tips using Android',
    'Video Rental Application in Android',
    'Quiz Application using Android',
    'Pharmacy Management System',
    'Mobile Pharmacy Application in Android',
    'Geographic Information System with Flood-Prone Location',
    'RFID-Based Student Monitoring System',
    'Home Appliances controlled by Android Smartphone',
    'Intelligent Traveler Locator using Google Map Application',
    'Bluetooth Controlled Robot using Android Mobile (CoE/CpE/IT/CS)',
    "Touch-Screen Based Point-Of-Sale System (POS)",
    'Sales and Inventory Monitoring System with SMS',
    'Weather Forecast Application using Android',
    'Cemetery Mapping and Information System',
  ]
}